;; -*- mode: emacs-lisp -*-
;; fsc.el: Autogenerated on Tue Apr 19 17:40:27 2011
(scala-fsc :classes "bin" :classpath
           '("lib/*.jar")
           :source "src" :clean-compile "ant clean all" :compile "ant")
